apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: ridezyproject-auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4001
              name: http
          envFrom:
            - configMapRef:
                name: ridezy-config
            - secretRef:
                name: ridezy-dev-secrets
          env:
            - name: PORT
              value: "4001"
            - name: SERVICE_NAME
              value: auth-service
          readinessProbe:
            httpGet:
              path: /health
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4001
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
