apiVersion: v1
kind: Service
metadata:
  name: blockchain
  labels:
    app: blockchain
spec:
  selector:
    app: blockchain
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
  type: ClusterIP
