apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain
  labels:
    app: blockchain
    tier: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
        tier: platform
    spec:
      containers:
        - name: blockchain
          image: ridezyproject-blockchain:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8545
              name: rpc
          readinessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "768Mi"
              cpu: "500m"
