apiVersion: v1
kind: Service
metadata:
  name: iot-service
  labels:
    app: iot-service
spec:
  selector:
    app: iot-service
  ports:
    - name: http
      port: 4012
      targetPort: 4012
  type: ClusterIP
