apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  labels:
    app: realtime-service
spec:
  selector:
    app: realtime-service
  ports:
    - name: http
      port: 4011
      targetPort: 4011
      nodePort: 30081
  type: NodePort
