apiVersion: v1
kind: Service
metadata:
  name: ride-service
  labels:
    app: ride-service
spec:
  selector:
    app: ride-service
  ports:
    - name: http
      port: 4009
      targetPort: 4009
  type: ClusterIP
