apiVersion: v1
kind: ConfigMap
metadata:
  name: ridezy-config
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongo:27017/ridezy"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  BLOCKCHAIN_RPC_URL: "http://blockchain:8545"
  MQTT_URL: "mqtt://mqtt:1883"
  INFLUX_URL: "http://influxdb:8086"
  INFLUX_ORG: "ridezy"
  INFLUX_BUCKET: "vehicle_data"
  REPUTATION_SERVICE_URL: "http://reputation-service:4007"
  AUTH_SERVICE_URL: "http://auth-service:4001/auth"
  RIDE_SERVICE_URL: "http://ride-service:4009/ride"
  LOCATION_SERVICE_URL: "http://ride-service:4009/location"
  MATCHING_SERVICE_URL: "http://ride-matching-service:4008/match"
  DRIVER_MATCHING_SERVICE_URL: "http://ride-matching-service:4008/driver"
  REALTIME_SERVICE_URL: "http://realtime-service:4011"
  PAYMENT_SERVICE_URL: "http://payment-service:4004"
  VEHICLE_SERVICE_URL: "http://vehicle-service:4003"
  IOT_SERVICE_URL: "http://iot-service:4012"
  ANALYTICS_SERVICE_URL: "http://analytics-service:4010"
  BLOCKCHAIN_SERVICE_URL: "http://blockchain-service:4002"
