apiVersion: v1
kind: Secret
metadata:
  name: ridezy-dev-secrets
type: Opaque
stringData:
  PRIVATE_KEY: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  INFLUX_TOKEN: "ridezy-local-dev-token"
  INFLUX_USERNAME: "ridezy"
  INFLUX_PASSWORD: "ridezy-password"
